######################################################################
#
# File name : tb_wave.do
# Created on: Mon Nov 06 21:10:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
